field: 8f7ecaad-4266-45ea-8bf7-cdae7f95fcfd
fieldLayouts:
  9123acbc-bdff-450c-9da1-9692dda39f40:
    tabs:
      -
        elements:
          -
            fieldUid: 22863b14-343a-43bb-b103-e4b1760fae78
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  22863b14-343a-43bb-b103-e4b1760fae78:
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: ''
    name: Images
    searchable: false
    settings:
      allowSelfRelations: false
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:244f7440-a428-4998-8c23-00991784b369'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:244f7440-a428-4998-8c23-00991784b369'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: images
name: Images
sortOrder: 2
