field: 8f7ecaad-4266-45ea-8bf7-cdae7f95fcfd
fieldLayouts:
  d498cb78-9029-4b0f-b113-a7cc3e3522c9:
    tabs:
      -
        elements:
          -
            fieldUid: cff3acc1-6b93-4ba9-8a60-b85608345beb
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  cff3acc1-6b93-4ba9-8a60-b85608345beb:
    contentColumnType: string(255)
    fieldGroup: null
    handle: video
    instructions: ''
    name: Video
    searchable: false
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
handle: video
name: Video
sortOrder: 1
