contentColumnType: string
fieldGroup: 04b3b4bb-5a04-4d55-a1fc-39e4312e4e96
handle: carousel
instructions: ''
name: Carousel
searchable: false
settings:
  contentTable: '{{%matrixcontent_carousel}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
