contentColumnType: string
fieldGroup: 04b3b4bb-5a04-4d55-a1fc-39e4312e4e96
handle: videos
instructions: ''
name: Videos
searchable: false
settings:
  contentTable: '{{%matrixcontent_videos}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
