enableVersioning: true
handle: five
name: Five
propagationMethod: all
siteSettings:
  8a2043ba-0ab6-482c-bb78-9c06b90e1891:
    enabledByDefault: true
    hasUrls: true
    template: home/five
    uriFormat: five
type: single
