enableVersioning: true
handle: four
name: Four
propagationMethod: all
siteSettings:
  8a2043ba-0ab6-482c-bb78-9c06b90e1891:
    enabledByDefault: true
    hasUrls: true
    template: home/four
    uriFormat: four
type: single
