enableVersioning: true
handle: stills
name: Stills
propagationMethod: all
siteSettings:
  8a2043ba-0ab6-482c-bb78-9c06b90e1891:
    enabledByDefault: true
    hasUrls: true
    template: projects/projects
    uriFormat: stills
type: single
