enableVersioning: true
handle: two
name: Two
propagationMethod: all
siteSettings:
  8a2043ba-0ab6-482c-bb78-9c06b90e1891:
    enabledByDefault: true
    hasUrls: true
    template: home/two
    uriFormat: two
type: single
